-services:

  nginx:
    build: .
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-cache:/var/cache/nginx
      - nginx-run:/var/run
      - nginx-logs:/var/log/nginx
    depends_on:
      - web
    restart: always

  web:
    image: guifranco/devops-lab:web
    container_name: web-app
    expose:
      - "80"
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  zabbix-db:
    image: mysql:8.0
    container_name: zabbix-db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - zabbix-db-data:/var/lib/mysql
    restart: always

  zabbix-server:
    image: zabbix/zabbix-server-mysql:ubuntu-6.4.0
    container_name: zabbix-server
    env_file:
      - .env
    environment:
      DB_SERVER_HOST: ${ZBX_DB_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - zabbix-db
    ports:
      - "10051:10051"
    restart: always

volumes:
  zabbix-db-data:
    name: zabbix-db-data

  nginx-cache:
    name: nginx-cache

  nginx-run:
    name: nginx-run

  nginx-logs:
    name: nginx-logs
