name: app

services:

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro

    depends_on:
      web:
        condition: service_healthy

    restart: unless-stopped


  web:
    image: guifranco/devops-lab:${IMAGE_TAG}
    container_name: web

    pull_policy: always

    expose:
      - "80"

    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s