name: CD

on:
  push:
    branches:
      - main

    paths:
      - "apps/site/**"
      - "apps/Dockerfile"
      - "apps/docker-compose.yml"
      - "apps/nginx/**"
      - ".github/workflows/app-cd.yml"

jobs:
  deploy:
    runs-on: [self-hosted, Linux, infra-dev]

    environment:
      name: production

    defaults:
      run:
        shell: bash
        working-directory: /home/guilherme/devops-lab/apps

    steps:
      - uses: actions/checkout@v4

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/Dockerfile
          push: true
          tags: |
            guifranco/devops-lab:web-${{ github.sha }}
            guifranco/devops-lab:web-prod

      - name: Deploy
        run: |
          ../deploy/app/deploy.sh web-${{ github.sha }}