name: Monitoring CD

concurrency:
  group: monitoring-production
  cancel-in-progress: false

on:
  workflow_dispatch:

  push:
    branches:
      - main

    paths:
      - "monitoring/**"
      - ".github/workflows/monitoring-cd.yml"

permissions:
  contents: read

jobs:
  deploy-monitoring:
    name: Deploy Monitoring Stack

    runs-on: [self-hosted, Linux, infra-dev]

    timeout-minutes: 20

    environment:
      name: production

    defaults:
      run:
        shell: bash
        working-directory: /home/guilherme/devops-lab/monitoring

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Docker daemon
        run: |
          set -euo pipefail

          docker info > /dev/null

      - name: Check disk space
        run: |
          set -euo pipefail

          df -h

      - name: Validate Docker Compose syntax
        run: |
          set -euo pipefail

          docker compose config > /dev/null

      - name: Build local monitoring images
        run: |
          set -euo pipefail

          docker compose \
            -p monitoring \
            build --no-cache

      - name: Deploy monitoring stack
        run: |
          set -euo pipefail

          ../deploy/monitoring/deploy-monitoring.sh

      - name: Wait for MySQL healthy
        run: |
          set -euo pipefail

          timeout 300 bash -c '
            until [ "$(docker inspect -f "{{.State.Health.Status}}" zabbix-db)" = "healthy" ]; do
              echo "Waiting MySQL..."
              sleep 5
            done
          '

      - name: Check Grafana health
        run: |
          set -euo pipefail

          timeout 180 bash -c '
            until curl -kfsS --connect-timeout 5 \
              http://localhost:3000/api/health \
              > /dev/null; do
              echo "Waiting Grafana..."
              sleep 5
            done
          '

      - name: Check Zabbix frontend
        run: |
          set -euo pipefail

          timeout 600 bash -c '
            until curl -kfsS --connect-timeout 5 \
              http://localhost:8080 \
              > /dev/null; do
              echo "Waiting Zabbix Frontend..."
              sleep 5
            done
          '

      - name: Validate monitoring containers
        run: |
          set -euo pipefail

          docker compose \
            -p monitoring \
            ps

      - name: Cleanup old unused images
        run: |
          set -euo pipefail

          docker image prune -af \
            --filter "until=72h"

      - name: Show monitoring status
        run: |
          set -euo pipefail

          docker ps \
            --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"

      - name: Show logs on failure
        if: failure()
        run: |
          set -euo pipefail

          docker compose \
            -p monitoring \
            logs --tail=200

          #Test Deployment
