name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build image
        run: docker build -t guifranco/devops-lab:web .

      - name: Push image
        run: |
          docker push guifranco/devops-lab:web
          docker tag guifranco/devops-lab:web guifranco/devops-lab:latest
          docker push guifranco/devops-lab:latest

      # 🔵 INSTALA TAILSCALE
      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      # 🔵 CONECTA NA VPN
      - name: Connect to Tailscale
        run: |
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTHKEY }}

      # 🔍 (opcional, mas recomendo pra debug)
      - name: Test connectivity
        run: |
          tailscale ip
          ping -c 4 100.125.200.108

      # 🚀 Deploy remoto via SSH (AGORA FUNCIONA)
      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/devops-lab

            echo "📥 Atualizando repo..."
            git pull

            echo "🚀 Deploy app..."
            chmod +x deploy.sh
            ./deploy.sh

            echo "📊 Deploy monitoring..."
            chmod +x deploy-monitoring.sh
            ./deploy-monitoring.sh